const API = "/api/plug/astrbot_plugin_content_companion/page";
const $ = (id) => document.getElementById(id);
async function call(path, options = {}) { const res = await fetch(API + path, {headers:{"Content-Type":"application/json"}, ...options}); const data = await res.json(); if (!res.ok) throw new Error(data.message || `请求失败（${res.status}）`); return data; }
function showNotice(text, error = false) { $("notice").textContent = text; $("notice").style.color = error ? "#b91c1c" : "#475569"; }
function renderStatus(payload) { const data = payload?.data || payload || {}; const summary = data.summary || {}; $("qzoneState").textContent = data.available ? (data.enabled ? "已启用" : "已连接") : "不可用"; $("qzoneReason").textContent = data.reason || summary.unavailable_reason || (data.available ? "QQ 空间链路正常" : "请检查陪伴插件与平台配置"); $("status").innerHTML = [["联动", data.delegated ? "陪伴主插件代理" : "未挂载"],["登录", data.available ? "可检查 Cookie" : "未连接"],["自动说说", summary.life_publish_enabled ? "开启" : "关闭"],["评论收件箱", summary.comment_inbox_enabled ? "开启" : "关闭"]].map(([k,v]) => `<div class="status"><span>${k}</span><b>${v}</b></div>`).join(""); }
function showManagedPage(managed) { $("managedPage").hidden = !managed; $("businessPage").hidden = managed; }
function openPluginManager() { try { window.top.location.assign("/#/plugins"); } catch (_) { window.location.assign("/#/plugins"); } }
async function loadStatus() { try { const payload = await call("/status"); const data = payload?.data || {}; if (data.managed_by_private_companion) { showManagedPage(true); return true; } showManagedPage(false); renderStatus(payload); return false; } catch (e) { showManagedPage(false); renderStatus({data:{available:false,reason:e.message}}); return false; } }
async function loadFeed() { $("feed").innerHTML = "<p>读取中...</p>"; try { const data = await call("/feed"); const items = data.items || data.data?.items || []; $("feed").innerHTML = items.length ? items.map(item => `<article class="post"><time>${item.time_text || item.create_time || ""}</time><div>${String(item.content || item.text || "").replace(/[&<>]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;"}[c]))}</div></article>`).join("") : "<p>没有读取到动态。</p>"; } catch (e) { $("feed").innerHTML = `<p>${e.message}</p>`; } }
async function loadProjects() { try { const data = await call("/projects"); const items = data.items || []; $("projectCount").textContent = String(data.total || 0); $("projects").innerHTML = items.length ? items.map(item => `<article class="post"><b>${String(item.title || "未命名作品").replace(/[&<>]/g, "")}</b><div>${String(item.work_type || "作品")} · ${String(item.status || "drafting")}</div><time>${Number(item.current_chars || 0)} / ${Number(item.target_chars || 0)} 字</time></article>`).join("") : "<p>书柜中还没有创作作品。</p>"; } catch (e) { $("projects").innerHTML = `<p>${e.message}</p>`; $("projectCount").textContent = "-"; } }
async function publish() { const content = $("content").value.trim(); if (!content) return showNotice("请先填写说说内容", true); try { await call("/action", {method:"POST", body:JSON.stringify({action:"publish", content})}); $("content").value = ""; showNotice("已提交发布"); await loadStatus(); } catch (e) { showNotice(e.message, true); } }
$("refresh").onclick = async () => { if (!(await loadStatus())) await loadProjects(); }; $("refreshFeed").onclick = loadFeed; $("publish").onclick = publish; $("openCompanion").onclick = openPluginManager; loadStatus().then((managed) => { if (!managed) loadProjects(); });
